name: build
on: [push]

jobs:
  build-stack:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - run: npm i
      - run: npx shadow-cljs release app --verbose
